import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased  relative`}
            style={{
                backgroundColor:"#E8E0DD",
            }}
        >
        <Image
            src="/svgs/Vector.svg"
            alt="Background decoration"
            width={1440}
            height={100}
            priority
            className="fixed top-0 left-0 w-full h-auto -z-10 pointer-events-none"
        />
        {children}
        </body>
        </html>
    );
}
